//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClueGen.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClueGen.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # List of common female names.
        ///# Copyright (c) January 1991 by Mark Kantrowitz.
        ///# 4987 names
        ///# Thanks to Bill.Ross for about 1000 additional names.
        ///# Version 1.3 (29-MAR-94)
        ///
        ///Abagael
        ///Abagail
        ///Abbe
        ///Abbey
        ///Abbi
        ///Abbie
        ///Abby
        ///Abigael
        ///Abigail
        ///Abigale
        ///Abra
        ///Acacia
        ///Ada
        ///Adah
        ///Adaline
        ///Adara
        ///Addie
        ///Addis
        ///Adel
        ///Adela
        ///Adelaide
        ///Adele
        ///Adelice
        ///Adelina
        ///Adelind
        ///Adeline
        ///Adella
        ///Adelle
        ///Adena
        ///Adey
        ///Adi
        ///Adiana
        ///Adina
        ///Adora
        ///Adore
        ///Adoree
        ///Adorne
        ///Adrea
        ///Adria
        ///Adriaens
        ///Adrian
        ///Adriana
        ///Adriane
        ///Adri [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string FemaleFirstNames {
            get {
                return ResourceManager.GetString("FemaleFirstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source: https://github.com/dominictarr/random-name/blob/master/names.txt
        ///
        ///Aaberg
        ///Aalst
        ///Aara
        ///Aaren
        ///Aarika
        ///Aaron
        ///Aaronson
        ///Ab
        ///Aba
        ///Abad
        ///Abagael
        ///Abagail
        ///Abana
        ///Abate
        ///Abba
        ///Abbate
        ///Abbe
        ///Abbey
        ///Abbi
        ///Abbie
        ///Abbot
        ///Abbotsen
        ///Abbotson
        ///Abbotsun
        ///Abbott
        ///Abbottson
        ///Abby
        ///Abbye
        ///Abdel
        ///Abdella
        ///Abdu
        ///Abdul
        ///Abdulla
        ///Abe
        ///Abebi
        ///Abel
        ///Abelard
        ///Abell
        ///Abercromby
        ///Abernathy
        ///Abernon
        ///Abert
        ///Abeu
        ///Abey
        ///Abie
        ///Abigael
        ///Abigail
        ///Abigale
        ///Abijah
        ///Abisha
        ///Abisia
        ///Abixah
        ///Abner
        ///Aborn
        ///Abott
        ///Abra
        ///Abraham
        ///Abr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # List of common male names.
        ///# Copyright (c) January 1991 by Mark Kantrowitz.
        ///# 2940 names
        ///# Thanks to Bill Ross for about 1000 additional names.
        ///# Version 1.3 (29-MAR-94)
        ///
        ///Aamir
        ///Aaron
        ///Abbey
        ///Abbie
        ///Abbot
        ///Abbott
        ///Abby
        ///Abdel
        ///Abdul
        ///Abdulkarim
        ///Abdullah
        ///Abe
        ///Abel
        ///Abelard
        ///Abner
        ///Abraham
        ///Abram
        ///Ace
        ///Adair
        ///Adam
        ///Adams
        ///Addie
        ///Adger
        ///Aditya
        ///Adlai
        ///Adnan
        ///Adolf
        ///Adolfo
        ///Adolph
        ///Adolphe
        ///Adolpho
        ///Adolphus
        ///Adrian
        ///Adrick
        ///Adrien
        ///Agamemnon
        ///Aguinaldo
        ///Aguste
        ///Agustin
        ///Aharon
        ///Ahmad
        ///Ahmed
        ///Ahmet
        ///A [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MaleFirstNames {
            get {
                return ResourceManager.GetString("MaleFirstNames", resourceCulture);
            }
        }
    }
}
